#!/bin/bash

set -ex

gcc -c picohttpparser.c -O3 -fPIC -msse4.2 -o ssepicohttpparser.o
gcc -c picohttpparser.c -O3 -fPIC -o picohttpparser.o
gcc -fPIC -shared -o libpicohttpparser.so picohttpparser.o ssepicohttpparser.o
